CREATE USER reading_user WITH PASSWORD '123';
ALTER ROLE reading_user WITH REPLICATION;

GRANT CONNECT ON DATABASE ecommerce TO reading_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reading_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO reading_user;
GRANT USAGE ON SCHEMA public TO reading_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO reading_user;
